#! /usr/bin/python2.7
import sys
import re
import subprocess
import json
from argparse import ArgumentParser, FileType, RawDescriptionHelpFormatter

class Context(object):
    # CONSTANTS
    DESCRIPTION = 'Python Grep Tool.'
    EPILOG = 'Author: Nic Roland\nEmail: nicroland9@gmail.com\nTwitter: @nicr9_'
    INDENT_RE = "^(\s*)"
    DEF_CLASS_RE = "^\s*(def|class) (.*?)[(:]"
    CONTEXT_COLOUR = "\033[93m%s\033[0m"
    LINE_SUM_COLOUR = "\033[91m%d:^\033[0m%s\033[91m$\033[0m"
    CONTEXT_CLEAN = "%s"
    LINE_SUM_CLEAN = "%d:^%s$"
    TAB = '\t'
    FOUR_SPACES = '    '
    GREP_TEMPLATE = 'grep ./ -Irne "%s" --include="*.py"'
    LINES = 'lines'

    # VARIABLES
    context = {}

    def __init__(self, args):
        parser = ArgumentParser(
                formatter_class = RawDescriptionHelpFormatter,
                description = self.DESCRIPTION,
                epilog = self.EPILOG
                )

        parser.add_argument(
                'search_term',
                default = None,
                nargs='?',
                type = str,
                help = 'Regex to search for'
                )

        parser.add_argument(
                '-f',
                '--file',
                default = None,
                type = str,
                help = 'Restrict search to specific file, wildcards are not yet supported.',
                dest = 'file_path'
                )

        parser.add_argument(
                '-l',
                '--line',
                type = int,
                help = 'Check context of a specific line in the file specified by -f',
                dest = 'file_line'
                )

        parser.add_argument(
                '-s',
                action = 'store_true',
                help = "Just print the context (don't display file number/text)",
                dest = 'summary'
                )

        parser.add_argument(
                '-d',
                action = 'store_true',
                help = "Display additional information to aid debugging.",
                dest = 'debug'
                )

        parser.add_argument(
                '-c',
                action = 'store_true',
                help = "Print out results without colours.",
                dest = 'clean'
                )

        config = parser.parse_args(args[1:])

        self.debug = config.debug
        self.summary = config.summary
        self._num_found = 0

        self.context_template = self.CONTEXT_CLEAN if config.clean else self.CONTEXT_COLOUR
        self.line_sum_template = self.LINE_SUM_CLEAN if config.clean else self.LINE_SUM_COLOUR

        if self.debug:
            print "=== CLI args ==="
            print args, '\n'
            config_pretty = {x:y for x, y in config._get_kwargs()}
            print "=== pygt config ==="
            print json.dumps(config_pretty, indent=4) + '\n'

        if config.file_line and config.file_path:
            self.get_context(config.file_path, config.file_line)
            self.print_dict(self.context)
        elif config.file_path is None and config.file_line is None:
            self.grep_for(config.search_term)
        else:
            parser.print_usage()

    def _format_line(self, line_number, line_text):
        return self.line_sum_template % (line_number, line_text)

    def _add_context(self, file_path, line_number, line_text, cntx_list):
        """
        Adds a line to the context tree.
        """
        # Step through context tree, creating nodes along the way
        pointer = self.context[file_path]
        for step in cntx_list:
            if step not in pointer:
                pointer[step] = {}
            pointer = pointer[step]
        if self.LINES not in pointer:
            pointer[self.LINES] = []

        # Add line_number + line_text to context
        line_ = self._format_line(line_number, line_text)
        pointer[self.LINES].append(line_)
        self._num_found += 1

    def get_indent(self, line):
        """
        Returns the indentation on a line as a substring.
        """
        match = re.match(self.INDENT_RE, line)
        indent = match.group(1)

        return re.sub(self.TAB, self.FOUR_SPACES, indent)

    def get_context(self, file_path, file_line):
        """
        Given the file path and the line number, determine the context of that line.
        """
        file_indx = file_line - 1

        # Add file path node to context
        if not file_path in self.context:
            self.context[file_path] = {}

        # Read in all lines up to and including the line given
        lines = []
        with open(file_path) as file_:
            for i, line in enumerate(file_):
                if i <= file_indx:
                    lines.append(line)
                else:
                    break
        assert len(lines) == file_line

        # Get indent of specified line
        init_indent = self.get_indent(lines[file_indx])

        results = []
        for line_no in range(file_indx-1, -1, -1):
            # Ignore empty lines
            if lines[line_no].strip():
                # Ignore lines that aren't a function or a class
                kw_match = re.search(self.DEF_CLASS_RE, lines[line_no])
                if kw_match:
                    # Get indent of relevant lines
                    next_indent = self.get_indent(lines[line_no])

                    # if line has less indentation add to results, change init_indent
                    if len(next_indent) < len(init_indent):
                        results.append(
                            ' '.join(kw_match.groups())
                            )
                        init_indent = next_indent

        # Add this entry to context tree
        self._add_context(
                file_path,
                file_line,
                lines[file_indx].strip('\n'),
                reversed(results)
                )

    def print_dict(self, obj, counter=0):
        for key, val in obj.iteritems():
            if isinstance(val, dict):
                print ' '*counter + self.context_template % key
                if self.LINES in val:
                    for row in val[self.LINES]:
                        if not self.summary:
                            print ' '*(counter+4), row
                    print
                self.print_dict(val, counter+4)
            elif isinstance(val, list):
                #for row in val:
                 #   print ' '*counter, row
                pass
            elif isinstance(val, str):
                    print ' '*counter, val
            else:
                print "%s type found: %s" % (type(val), val)

    def grep_for(self, exp):
        """
        Execute a grep command to search for the given expression.
        Then print out the context for each result.
        """
        results = []
        try:
            response = subprocess.check_output(
                    [self.GREP_TEMPLATE % exp],
                    shell=True
                    )
            results = response.splitlines()

            if self.debug:
                print "=== Grep results ==="
                print response, "Total results: %d\n" % len(results)
        except subprocess.CalledProcessError, e:
            if e.returncode == 1:
                print "Couldn't find anything matching '%s'" % exp
            else:
                print "Whoops, grep returned errorcode %d" % e.errorcode
            sys.exit()

        for row in results:
            file_name, file_line = row.split(':')[:2]

            self.get_context(file_name, int(file_line))
        self.print_dict(self.context)

        if self.debug:
            print "Total found: %d" % self._num_found

if __name__ == "__main__":
    x = Context(sys.argv)
